
package applica;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://applica/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param data
     * @param data2
     */
    @WebMethod
    @RequestWrapper(localName = "savePerson", targetNamespace = "http://applica/", className = "applica.SavePerson")
    @ResponseWrapper(localName = "savePersonResponse", targetNamespace = "http://applica/", className = "applica.SavePersonResponse")
    @Action(input = "http://applica/HelloWorld/savePersonRequest", output = "http://applica/HelloWorld/savePersonResponse")
    public void savePerson(
        @WebParam(name = "data", targetNamespace = "")
        UiPerson data,
        @WebParam(name = "data2", targetNamespace = "")
        List<UiPerson> data2);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://applica/", className = "applica.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://applica/", className = "applica.DeletePersonResponse")
    @Action(input = "http://applica/HelloWorld/deletePersonRequest", output = "http://applica/HelloWorld/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

}
